# Generated by Django 5.0.6 on 2024-08-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', help_text='Укажите название категории', max_length=100, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание категории', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название продукта', max_length=100, verbose_name='Наименование продукта')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание продукта', null=True, verbose_name='Описание продукта')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='catalog/images', verbose_name='Фото')),
                ('price', models.FloatField(help_text='Укажите стоимость продукта', verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Добавьте дату создания продукта', verbose_name='Дата создания продукта')),
                ('updated_at', models.DateField(auto_now=True, help_text='Добавьте дату изменения продукта', verbose_name='Дата последнего изменения продукта')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Укажите номер версии продукта', verbose_name='Номер версии')),
                ('version_name', models.CharField(help_text='Укажите название версии', max_length=100, verbose_name='Наименование версии')),
                ('is_current_version', models.BooleanField(default=False, help_text='Укажите, является ли текущей версией продукта', verbose_name='Текущая версия')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия продукта',
                'verbose_name_plural': 'Версии продуктов',
                'ordering': ['-version_number'],
            },
        ),
    ]
